### ISSUE TITLE
Can we beat the Ender Dragon ?

### ISSUE THREAD

**Issue by SergeantPeppers** [drewhoener/JWSuggestions#40] opened 2015-05-05 20:07 UTC
It would be cool. When the mineworld is reset every saturday, the Ender isn't generated. Why can't we generate the Ender, so anyone would be able to find the stronghold, go through the Ender Portal, coming in the Ender, and kill the Ender Dragon.

I thought this because last saturday I wanted to beat the Ender Dragon to get the dragon egg :/

**Comment by littletntman** [comment] 2015-05-05 20:31
Well there's /warp End so someone can have more then 1 egg and it's kinda unfair.

**Comment by johnnywoof** [comment] 2015-05-07 16:51
I believe this was discussed before, though I'm not sure why this idea was rejected before.

**Comment by Spazgazum** [comment] 2015-05-08 01:09
I think it would be cool.

**Comment by SergeantPeppers** [comment] 2015-05-08 20:44
I don't get your point, littletntman... When you beat the Ender Dragon one time, it's over. The End must be reseted to defeat the Dragon again.

**Comment by Spazgazum** [comment] 2015-05-08 20:47
Also,  /warp end  is only for buildworld end. 
He is referring to mineworld.

**Comment by johnnywoof** [comment] 2015-05-19 16:45
Duplicate of https://github.com/drewhoener/JWSuggestions/issues/3

**Closed by johnnywoof** 2015-05-19 16:45 UTC
Labels: Mineworld
