### ISSUE TITLE
/send

### ISSUE THREAD

**Issue by littletntman** [drewhoener/JWSuggestions#26] opened 2015-04-21 01:02 UTC
Send an item in your hand to another player

**Comment by johnnywoof** [comment] 2015-04-21 13:42
There is currently a trade system under development which has this feature.

**Comment by littletntman** [comment] 2015-04-21 21:40
Thank you for your comment :)

**Comment by littletntman** [comment] 2015-04-21 21:41
And your awesome server

**Comment by johnnywoof** [comment] 2015-04-24 15:27
Arguable a duplicate of https://github.com/drewhoener/JWSuggestions/issues/29

**Closed by johnnywoof** 2015-04-24 15:27 UTC
Labels: Will Implement
